### ISSUE TITLE
Fails when `OTEL_EXPORTER_OTLP_HEADERS` is unset: `'NoneType' object has no attribute 'split'`

### ISSUE THREAD

**Issue by AKarbas** [StephenGoodall/OTLP-GitHubAction-Exporter#28]
**To Reproduce**
Run `v3.2.3` and point to an otel endpoint that needs no additional headers (I'm running self-hosted).

Workflow file:
```yml
name: OpenTelemetry - Export OTel Traces and Logs from Workflow Runs

on:
  workflow_run: # Run after all other workflows finish
    workflows: ["*"]
    types: [completed]

permissions:
  actions: read
  checks: read

env:
  ACTION_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  OTEL_EXPORTER_OTLP_ENDPOINT: <...>
  OTLP_PROTOCOL: HTTP
  WORKFLOW_RUN_ID: ${{ github.event.workflow_run.id }}
  WORKFLOW_RUN_NAME: ${{ github.event.workflow_run.name }}
  GITHUB_DEBUG: true

jobs:
  OTLP-GitHubAction-Exporter:
    name: OTLP GitHubAction Exporter
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Run OTLP GitHubAction Exporter
        # https://github.com/StephenGoodall/OTLP-GitHubAction-Exporter/releases/tag/v3.2.3
        uses: StephenGoodall/OTLP-GitHubAction-Exporter@22db272441d02be2aba3851a62a5385a43fb2d1f

```

Logs:
```
Run StephenGoodall/OTLP-GitHubAction-Exporter@22db272441d02be2aba3851a62a5385a43fb2d1f
  env:
    ACTION_TOKEN: ***
    OTEL_EXPORTER_OTLP_ENDPOINT: <...>
    OTLP_PROTOCOL: <...>
    WORKFLOW_RUN_ID: <...>
    WORKFLOW_RUN_NAME: <...>
    GITHUB_DEBUG: true
/usr/bin/docker run --name <...> --label <...> --workdir /github/workspace --rm -e "ACTION_TOKEN" -e "OTEL_EXPORTER_OTLP_ENDPOINT" -e "OTLP_PROTOCOL" -e "WORKFLOW_RUN_ID" -e "WORKFLOW_RUN_NAME" -e "GITHUB_DEBUG" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB
Traceback (most recent call last):
Running on DEBUG mode
  File "/app/exporter.py", line 57, in <module>
    HEADERS_SPLIT = OTEL_EXPORTER_OTLP_HEADERS.split(",")
AttributeError: 'NoneType' object has no attribute 'split'
```
